
export const SET_ERROR = 'SET_ERROR'
export const SET_PROJECTS = 'SET_PROJECTS'
export const SET_PROJECT = 'SET_PROJECT'
export const SET_DEVELOPERS = 'SET_DEVELOPERS'
export const SET_COMPONENTS = 'SET_COMPONENTS'
export const SET_JIRA_ISSUE_TYPES = 'SET_JIRA_ISSUE_TYPES'

export const SET_WIZARD_COMMON_CONTAINER = 'SET_WIZARD_COMMON_CONTAINER'
export const SET_WIZARD_BUG_CONTAINER = 'SET_WIZARD_BUG_CONTAINER'
export const SET_WIZARD_CHANGE_CONTAINER = 'SET_WIZARD_CHANGE_CONTAINER'
export const SET_WIZARD_FORM_CONTAINER = 'SET_WIZARD_FORM_CONTAINER'
export const SET_WIZARD_NEW_CONTAINER = 'SET_WIZARD_NEW_CONTAINER'

export const CLEAR_BUG_CONTAINER = 'CLEAR_BUG_CONTAINER'
export const CLEAR_CHANGE_CONTAINER = 'CLEAR_CHANGE_CONTAINER'
export const CLEAR_NEW_CONTAINER = 'CLEAR_NEW_CONTAINER'
export const CLEAR_REFACTORING_CONTAINER = 'CLEAR_REFACTORING_CONTAINER'
